export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-cream-500 pt-32">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="bg-white border-4 border-black comic-shadow-lg p-8 sm:p-12">
          <h1 className="text-4xl sm:text-5xl font-black text-gray-900 mb-4 uppercase tracking-tight">
            Terms of Service
          </h1>
          <p className="text-gray-600 mb-12">Last updated: January 2026</p>
          
          <div className="space-y-8 text-gray-900">
          {/* Introduction */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Introduction</h2>
            <p className="leading-relaxed">
              These Terms of Service (&quot;Terms&quot;) govern your access to and use of AutoMitra AI&apos;s website, platform, and services. By using our services, you agree to these Terms.
            </p>
          </section>

          {/* Use of Services */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Use of Services</h2>
            <p className="leading-relaxed">
              You agree to use our services only for lawful purposes and in compliance with applicable laws. You must not misuse, disrupt, or attempt to gain unauthorized access to our systems.
            </p>
          </section>

          {/* Service Availability */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Service Availability</h2>
            <p className="leading-relaxed">
              We strive to ensure reliable service but do not guarantee uninterrupted availability. Features and functionality may change as the platform evolves.
            </p>
          </section>

          {/* AI & Automation Disclaimer */}
          <section>
            <h2 className="text-2xl font-bold mb-4">AI & Automation Disclaimer</h2>
            <p className="leading-relaxed">
              AutoMitra AI provides AI-powered voice and messaging automation tools. Outputs generated by AI are not guaranteed to be error-free. You are responsible for reviewing and validating outputs before business use.
            </p>
          </section>

          {/* Intellectual Property */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Intellectual Property</h2>
            <p className="leading-relaxed">
              All content, software, branding, and materials on this website are the property of AutoMitra AI and may not be copied, modified, or distributed without permission.
            </p>
          </section>

          {/* Payments & Pricing */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Payments & Pricing</h2>
            <p className="leading-relaxed">
              Pricing, where applicable, will be communicated directly and may vary based on usage and customization. All payment terms will be agreed upon separately.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
            <p className="leading-relaxed">
              To the maximum extent permitted by law, AutoMitra AI shall not be liable for indirect, incidental, or consequential damages arising from the use of our services.
            </p>
          </section>

          {/* Termination */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Termination</h2>
            <p className="leading-relaxed">
              We reserve the right to suspend or terminate access if these Terms are violated.
            </p>
          </section>

          {/* Governing Law */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Governing Law</h2>
            <p className="leading-relaxed">
              These Terms are governed by the laws of India, without regard to conflict of law principles.
            </p>
          </section>

          {/* Changes to Terms */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Changes to Terms</h2>
            <p className="leading-relaxed">
              We may update these Terms from time to time. Continued use of the services indicates acceptance of updated Terms.
            </p>
          </section>

          {/* Contact Information */}
          <section>
            <h2 className="text-2xl font-bold mb-4">Contact Information</h2>
            <p className="leading-relaxed">
              For any questions regarding these Terms, contact us at:{' '}
              <a href="mailto:contact@automitra.ai" className="text-blue-600 hover:underline">
                contact@automitra.ai
              </a>
            </p>
          </section>
        </div>
        </div>
      </div>
    </main>
  );
}
